# Generated by Django 2.0.5 on 2018-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'article', 'verbose_name_plural': 'article'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_time',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
